[build]
  base = "examples/docs/"
  functions = "functions/"
  publish = "dist/"
  command = "mkdir /opt/build/repo/examples/docs/bin && export PATH=\"/opt/build/repo/examples/docs/bin:$PATH\" && echo $PATH && curl https://static.lamdera.com/bin/linux/lamdera -o /opt/build/repo/examples/docs/bin/lamdera && chmod a+x /opt/build/repo/examples/docs/bin/lamdera && export ELM_HOME=\"$NETLIFY_BUILD_BASE/cache/elm\" && (cd ../../ && npm install --no-optional && npm run build:generator) && npm install && npx --no-install elm-tooling install && npx elm-pages build && cp ./elm-stuff/elm-pages/elm.js functions/render/elm-pages-cli.js && (cd functions/process-url && npm i)"

[[redirects]]
  from = "/screenshot/*"
  to = "/.netlify/functions/screenshot"
  status = 200

[dev]
  command = "npm start"
  targetPort = 1234
  autoLaunch = true
  framework = "#custom"